### ISSUE TITLE
Installation clarifications

### ISSUE THREAD

**Issue by ivalaginja** [lorenaacuna/GASTLI#5]
This is currently the biggest blocker for my review in https://github.com/openjournals/joss-reviews/issues/7288.

## Installation instructions structure

First and foremost, considering that you give very detailed instructions on how to install your package on several OS, and specifically different MacOS processors, I am missing a top-level overview of the installation process for users who don’t need the detailed instructions. For example, this could be:

> The installation of `gastli` requires Python version 9 or higher, with the dependencies `ipython`, `numpy` and `jupyter`, as well as a Fortran compiler. The `gastli` package itself can be installed with pip. You will also need to download a zip file of input data required by the package.

Then I would add a warning/note about the processor details, so that people know up front that this is something to look out for.

Only then would I go into detailed installation instructions, where I think you can separate:
1. The conda environment setup with the installation of Python, its dependencies, and gastli itself - this should be pretty much the same on any OS, provided that a conda distribution is already installed.
2. The input data download, again the same across all OS.
3. A Fortran compiler installation - here is where you need to separate between Linux, MacOS with Intel chips and MacOS with Apple chips.

The result of this would be that users who are experienced enough with similar installations can just get the gist of things and move on. You also warn about the processor bifurcation immediately in the beginning, so users on a MacOS will know to be mindful when starting the installation. And finally, it still gives you the space to provide all the details about the different installation procedures.

## General comments

Apart from the above, below I am providing a couple of review questions on things that are still unclear to me. If I simply didn't understand something well, I apologize - I will be happy to rectify my comments with any new information you can give me.

1. You recommend to install Python, but then you proceed to do a new Python installation in a conda environment for gastli. Why? The system will only ever use one or the other as far as I know, which means that you just want the Python installation in the conda environment I believe?
2. Have you considered providing a conda recipe for the part that requires a conda environment setup? For example something like an `environment.yml` file that would install all the conda installations at once instead of having to type them manually? Since you have very few requirements, you could also just provide the one line (instead of a full `environment.yml` file) to create the conda environment with the right dependencies automatically: `conda create -n gastli python=3.10 ipython numpy jupyter`, and then the line that installs gastli: `pip install gastli==0.9.1`. If you were to use a `environment.yml` file, it would be able to run both of these things at once - the two steps are so simple though that the use of such a file is not necessarily warranted.
3. I also just realized that your `gastli` pip package already lists requirements, so you might also just put any dependencies in there instead of having the user install them one by one. Or have a conda recipe that includes your pip package, as I mentioned in 2). Either way, it would make the installation easier.
4. In the section where you describe the installation with Rosetta, you don’t even mention a dedicated conda environment, you just say to “install the following packages in miniconda3” - package installations should always be directed to a specific environment, in your case the `gastli`/`GASTLI_env` environment.
5. You recommend to work with a conda env but you also recommend to install `gcc` with homebrew instead of conda. Why? There could be a good reason to have a system-wide `gcc` install for your purposes with homebrew, but at first sight, it seems more logical to contain all dependencies for GASTLI in the same conda env. `gcc` seems to be installable through conda-forge, have you tried that?
6. You claim: “The installation of GASTLI on Apple machines with the M1/M2/M3 chip requires Intel emulation with Rosetta.” It would be useful to have a concrete example that triggers the mentioned error so that the user can quickly determine if the Rosetta installation is indeed required for them.
7. Also, does the above mean that option 2) with the disk image doesn’t actually work on M1/M2/M3 machines?
8. I am on a MacOS 12.2 Monterey using an M1 and tried to use the disk image solution because it seems so much easier than to set up Rosetta. However, the disk image installation doesn’t seem to be recognized when I run `import gastli.Coupling as cpl` in an ipython terminal from my gastli conda environment. Did you try an installation like this yourself, is there more to it than just running the installer? For reference, the error message I get:
```
ImportError: dlopen(/Users/ilaginja/opt/miniconda3/envs/gastli3/lib/python3.10/site-packages/gastli/fortinput.cpython-310-darwin.so, 0x0002): Library not loaded: /usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib
  Referenced from: /Users/ilaginja/opt/miniconda3/envs/gastli3/lib/python3.10/site-packages/gastli/fortinput.cpython-310-darwin.so
  Reason: tried: '/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file)
```

**Comment by lorenaacuna** [comment]
Thanks @ivalaginja for the feedback. I start by addressing comment 8): 

> I am on a MacOS 12.2 Monterey using an M1 and tried to use the disk image solution because it seems so much easier than to set up Rosetta. However, the disk image installation doesn’t seem to be recognized when I run import gastli.Coupling as cpl in an ipython terminal from my gastli conda environment. Did you try an installation like this yourself, is there more to it than just running the installer? For reference, the error message I get:

This is the message we get if we try to install GASTLI in Apple Silicon with the gfortran native ARM64 installation. This is not explicitly said in the disk image subsection of the installation documentation, but the version I think you need to install of gfortran is the Intel one, not the ARM64. I need to confirm this with the co-author that wrote this sub-section of the documentation. In the meantime, can you try to uninstall your current ARM64 gfortran and install the Intel one? If that does not work, please let me know. 

I continue to address the other questions in the following comments.

**Comment by ivalaginja** [comment]
Great, will do! Thanks for the fast feedback!

**Comment by lorenaacuna** [comment]
I changed the installation page in the documentation to address the suggestions for the structure. The installation page now follows the structure:
- overview of requirements
- table of content for Fortran installation for different OS
- warning for Apple Silicon Users
- usual installation with conda and pip. We recommend the users to use these.

**Comment by lorenaacuna** [comment]
Answer to comments 1), 2) and 3):

> You recommend to install Python, but then you proceed to do a new Python installation in a conda environment for gastli. Why? The system will only ever use one or the other as far as I know, which means that you just want the Python installation in the conda environment I believe?

Exactly. We recommend the user to use conda or venv environments to avoid conflicts, but it is up to the user to decide this. I have modified that part of the text as "If you decide to create a new conda environment (for example, “GASTLI_env”), [...]" just to clarify that the use of conda is optional.

> Since you have very few requirements, you could also just provide the one line (instead of a full environment.yml file) to create the conda environment with the right dependencies automatically: conda create -n gastli python=3.10 ipython numpy jupyter, and then the line that installs gastli: pip install gastli==0.9.1.

ipython and jupyter are not required to use GASTLI, I removed these from the docs. Now the user just needs to 1) create a conda/venv environment (if they choose to) and 2) run pip install gastli==0.9.1

> I also just realized that your gastli pip package already lists requirements, so you might also just put any dependencies in there instead of having the user install them one by one. 

Yes, this is why the .yml file is not so necessary. numpy, which was mentioned in the documentation before, is already in the requirements. I removed the mention of numpy together with ipython and jupyter.

**Comment by lorenaacuna** [comment]
Answer to comment 4):

> In the section where you describe the installation with Rosetta, you don’t even mention a dedicated conda environment, you just say to “install the following packages in miniconda3” - package installations should always be directed to a specific environment, in your case the gastli/GASTLI_env environment.

First the steps to install miniconda3 need to be followed. Then once the user has miniconda3 working with Rosetta, they can install GASTLI as usual. I removed the package part and added a clarification at the end that the user can create a conda/venv environment to avoid conflicts.

**Comment by lorenaacuna** [comment]
Answers to comments 6) and 7):

> You claim: “The installation of GASTLI on Apple machines with the M1/M2/M3 chip requires Intel emulation with Rosetta.” It would be useful to have a concrete example that triggers the mentioned error so that the user can quickly determine if the Rosetta installation is indeed required for them.

I added instructions on how to check if the user needs to follow the instructions for Apple Silicon in the very first warning in the installation front page. This includes an example of the error message that we get when trying to install GASTLI in the arm64 architecture.

> Also, does the above mean that option 2) with the disk image doesn’t actually work on M1/M2/M3 machines?

No, the disk image solution is an alternative to Rosetta for Apple Silicon users, so it should work on the M1-M3 machines.

**Comment by lorenaacuna** [comment]
Answer to comment 5):

> You recommend to work with a conda env but you also recommend to install gcc with homebrew instead of conda. Why? There could be a good reason to have a system-wide gcc install for your purposes with homebrew, but at first sight, it seems more logical to contain all dependencies for GASTLI in the same conda env. gcc seems to be installable through conda-forge, have you tried that?

The installation of gcc/gfortran is quite tricky. If the user chooses to install gcc through conda-forge instead of homebrew, the compilation of the fortran backend done by Python's packages (that is meson and pip in the case of GASTLI) may not work, depending on the OS. We noticed that using homebrew is more successful in these cases, so this is what we recommend.

**Comment by lorenaacuna** [comment]
@ivalaginja I will close this issue once you confirm that you could install it in your machine. I also want to wait for the co-author that wrote the Apple Silicon installation with disk images to clarify this part of the documentation. He'll get back next week.

**Comment by ivalaginja** [comment]
@lorenaacuna thanks a lot for the detailed answers! I will look at them in detail shorty, it looks like all of my questions were addressed. I'll let you know!

**Comment by ivalaginja** [comment]
> I changed the installation page in the documentation to address the suggestions for the structure. The installation page now follows the structure:
> 
>     * overview of requirements
> 
>     * table of content for Fortran installation for different OS
> 
>     * warning for Apple Silicon Users
> 
>     * usual installation with conda and pip. We recommend the users to use these.

This is so much better now, amazing! :D

**Comment by ivalaginja** [comment]
> Answer to comment 4):
> 
> > In the section where you describe the installation with Rosetta, you don’t even mention a dedicated conda environment, you just say to “install the following packages in miniconda3” - package installations should always be directed to a specific environment, in your case the gastli/GASTLI_env environment.
> 
> First the steps to install miniconda3 need to be followed. Then once the user has miniconda3 working with Rosetta, they can install GASTLI as usual. I removed the package part and added a clarification at the end that the user can create a conda/venv environment to avoid conflicts.

This is also a lot clearer in the docs now, thank you!

**Comment by ivalaginja** [comment]
> Answer to comment 5):
> 
> > You recommend to work with a conda env but you also recommend to install gcc with homebrew instead of conda. Why? There could be a good reason to have a system-wide gcc install for your purposes with homebrew, but at first sight, it seems more logical to contain all dependencies for GASTLI in the same conda env. gcc seems to be installable through conda-forge, have you tried that?
> 
> The installation of gcc/gfortran is quite tricky. If the user chooses to install gcc through conda-forge instead of homebrew, the compilation of the fortran backend done by Python's packages (that is meson and pip in the case of GASTLI) may not work, depending on the OS. We noticed that using homebrew is more successful in these cases, so this is what we recommend.

Aha! Good to know. Thanks for explaining!

**Comment by ivalaginja** [comment]
I am currently going through the installation with Rosetta  for a M1/M2/M3 Mac and have a couple of questions and comments:

1. Twice in the installation instructions, you instruct to "cut and paste" -> do you really mean cut, or do you mean copy and paste? If it's indeed cut, it might be worth to clarify in parentheses `(copy and remove)`, if you don't actually mean cut, then replace the word with paste. I have to admit that as someone who has never used Rosetta before, it is unclear which of the two is needed.

The two lines are:
- https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L70
- https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L103

2. [Here](https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L51), you say you'll assume people already have anaconda installed in their main terminal. Since most people are very confused between anaconda, miniconda and conda, here again it would be good to specify something like: "[...] you already installed ``anaconda`` or ``miniconda``  in your M1/M2/M3 terminal [...]".

3. Claim: https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L129 - but how will I actually know? Might be worth adding half a sentence describing how exactly the user will know.

4. The most important comment is, actually, that when I ran `softwareupdate --install-rosetta`, I get the following output - note the error message in the second to last line before it claims it finished successfully:
```bash
maintenncesMBP6:~ ilaginja$ softwareupdate --install-rosetta
I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
Type A and press return to agree: A
2024-11-24 20:33:44.639 softwareupdate[39894:12294479] Package Authoring Error: 002-57052: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
Install of Rosetta 2 finished successfully
```
The result is that I do not have the iTerm app on my machine. I tried googling this but wasn't able to understand what is happening. Would you have any clues?

**Comment by lorenaacuna** [comment]
> This is the message we get if we try to install GASTLI in Apple Silicon with the gfortran native ARM64 installation. This is not explicitly said in the disk image subsection of the installation documentation, but the version I think you need to install of gfortran is the Intel one, not the ARM64. I need to confirm this with the co-author that wrote this sub-section of the documentation. In the meantime, can you try to uninstall your current ARM64 gfortran and install the Intel one? If that does not work, please let me know.

My co-author got back about the disk image solution: If you have the M1/M2/M3 Mac OS, you need to install the ARM64 (not Intel, as I said in a previous message). For them, the disk image worked just "out of the box", following the instructions in FX Coudert's repository. 

@ivalaginja we suggest to check what fortran binary is being called by default by running the command `which gfortran` on your terminal. If it is not the the arm64 version that you installed, then you need to change the path of the default gfortran to the arm64. I'm adding a few words about this in the documentation. I'll be back to this thread to address the comments about the Rosetta installation.

**Comment by lorenaacuna** [comment]
I address the Rosetta installation questions: 

> I am currently going through the installation with Rosetta for a M1/M2/M3 Mac and have a couple of questions and comments:
> 
> 1. Twice in the installation instructions, you instruct to "cut and paste" -> do you really mean cut, or do you mean copy and paste? If it's indeed cut, it might be worth to clarify in parentheses `(copy and remove)`, if you don't actually mean cut, then replace the word "cut" with "copy". I have to admit that as someone who has never used Rosetta before, it is unclear which of the two is needed.
> The two lines are:
> 
> * https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L70
> * https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L103

We mean cut, i.e copy and remove. I clarified this in the documentation.

> 
> 2. [Here](https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L51), you say you'll assume people already have anaconda installed in their main terminal. Since most people are very confused between anaconda, miniconda and conda, here again it would be good to specify something like: "[...] you already installed `anaconda` or `miniconda`  in your M1/M2/M3 terminal [...]".

Ok, added to the documentation.

> 3. Claim: https://github.com/lorenaacuna/GASTLI/blob/de99c5ca4851d1b54d6cdf155bb1ce562b02cad2/docs/source/macos_arm64_install.rst?plain=1#L129
>     - but how will I actually know? Might be worth adding half a sentence describing how exactly the user will know.

It is displayed in the terminal when you open it. When I open my iTerm_Rosetta, this is the first message that is shown:

```
Last login: Mon Nov 25 10:04:04 on ttys000
Running on Rosetta using miniconda3

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) mac-n-176:~ acuna$ 

```

I added this to the documentation.

> 4. The most important comment is, actually, that when I ran `softwareupdate --install-rosetta`, I get the following output - note the error message in the second to last line before it claims it finished successfully:
> 
> ```shell
> maintenncesMBP6:~ ilaginja$ softwareupdate --install-rosetta
> I have read and agree to the terms of the software license agreement. A list of Apple SLAs may be found here: http://www.apple.com/legal/sla/
> Type A and press return to agree: A
> 2024-11-24 20:33:44.639 softwareupdate[39894:12294479] Package Authoring Error: 002-57052: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute
> Install of Rosetta 2 finished successfully
> ```
> 
> The result is that I do not have the iTerm app on my machine. I tried googling this but wasn't able to understand what is happening. Would you have any clues?

I have Rosetta installed in the terminal in my OS Monterey M2 chip and I never had this message. Not having the iTerm app in the directory "Applications" of your Mac should not be a problem (I don't have it either myself). Use the default terminal app instead. In my case it is in Applications > Utilities, and it is named "Terminal". If you have the same, follow the instructions in the documentation with "Terminal" instead of "iTerm". 

Then for the installation of Rosetta, you may already have Rosetta 2 installed in your system if you tried to run an Intel app before (it is downloaded automatically, see: https://support.apple.com/en-us/102527). If that's the case, you should be able to see the option "Open using Rosetta" under "Get Info" when your right click on the Terminal app. 

Let me know if that works.

**Comment by ivalaginja** [comment]
> > This is the message we get if we try to install GASTLI in Apple Silicon with the gfortran native ARM64 installation. This is not explicitly said in the disk image subsection of the installation documentation, but the version I think you need to install of gfortran is the Intel one, not the ARM64. I need to confirm this with the co-author that wrote this sub-section of the documentation. In the meantime, can you try to uninstall your current ARM64 gfortran and install the Intel one? If that does not work, please let me know.
> 
> My co-author got back about the disk image solution: If you have the M1/M2/M3 Mac OS, you need to install the ARM64 (not Intel, as I said in a previous message). For them, the disk image worked just "out of the box", following the instructions in FX Coudert's repository.
> 
> @ivalaginja we suggest to check what fortran binary is being called by default by running the command `which gfortran` on your terminal. If it is not the the arm64 version that you installed, then you need to change the path of the default gfortran to the arm64. I'm adding a few words about this in the documentation. I'll be back to this thread to address the comments about the Rosetta installation.

Unfortunately, this still doesn't work. When I run `which gfortran`, it now returns `/usr/local/bin/gfortran` as expected, and I made sure to install the ARM64 version. Not sure what's happening there.

Still working on the installation with Rosetta.

**Comment by ivalaginja** [comment]
> I have Rosetta installed in the terminal in my OS Monterey M2 chip and I never had this message. Not having the iTerm app in the directory "Applications" of your Mac should not be a problem (I don't have it either myself). Use the default terminal app instead. In my case it is in Applications > Utilities, and it is named "Terminal". If you have the same, follow the instructions in the documentation with "Terminal" instead of "iTerm".
> 
> Then for the installation of Rosetta, you may already have Rosetta 2 installed in your system if you tried to run an Intel app before (it is downloaded automatically, see: https://support.apple.com/en-us/102527). If that's the case, you should be able to see the option "Open using Rosetta" under "Get Info" when your right click on the Terminal app.
> 
> Let me know if that works.

This worked, thanks for the guidance. Maybe you could put this information in a "Warning" or "Note" box in the documentation too? Also, I first had to close all my open Terminal windows to make this work.

For the docs, I would urge you to remove the note about the conda env for gastli being optional which you have at the end of the Rosetta installation section. You go to great lengths having people install conda, so imho they should also use it. It is a good coding practice anyway so let's endorse it :)

That being said, I would like to see a clarification on the Installation page about the sequence of things. YOu currently have: "If you do not have either of the first two requirements, we offer an installation guide for different OS below: [...]"

Instead I would suggest to give very clear instructions for installation:
"To get everything installed, first make sure to follow the Fortran installation process appropriate for your OS, then proceed with the GASTLI package installation." -> I would also make a title for the Fortran installation section here on the same level like the title "Installation of GASTLI’s Python package". This way it is clear that these are two separate steps that need to be done in sequence to get everything done.

I will report back with my further tests.

**Comment by lorenaacuna** [comment]
> This worked, thanks for the guidance. Maybe you could put this information in a "Warning" or "Note" box in the documentation too? Also, I had to quite my Terminal to make this work which is logical to me once I realized you cannot run both architectures in separate windows at the same time apparently.
> 
> For the docs, I would urge you to remove the note about the conda env for gastli being optional which you have at the end of the Rosetta installation section. You go to great lengths having people install conda, so imho they should also use it. It is a good coding practice anyway so let's endorse it :)
> 
> That being said, I would like to see a clarification on the Installation page about the sequence of things. YOu currently have: "If you do not have either of the first two requirements, we offer an installation guide for different OS below: [...]"
> 
> Instead I would suggest to give very clear instructions for installation:
> "To get everything installed, first make sure to follow the Fortran installation process appropriate for your OS, then proceed with the GASTLI package installation." -> I would also make a title for the Fortran installation section here on the same level like the title "Installation of GASTLI’s Python package". This way it is clear that these are two separate steps that need to be done in sequence to get everything done.
> 

I'm adding these suggestions to the documentations now. I'm glad you could make everything work with Rosetta

**Comment by lorenaacuna** [comment]
> Everything seems to run as expected. Do you have an idea though why the pytests don't run when I call them locally?
> 
> <img alt="Screenshot 2024-12-01 at 21 33 27" width="668" src="https://private-user-images.githubusercontent.com/29508965/391363799-655c171e-cb76-40da-8160-e0b384d1bac0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTYwMjAsIm5iZiI6MTczMzE1NTcyMCwicGF0aCI6Ii8yOTUwODk2NS8zOTEzNjM3OTktNjU1YzE3MWUtY2I3Ni00MGRhLTgxNjAtZTBiMzg0ZDFiYWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYjFlNzdjYjk1ZjU2YjJmMDA0Mzc2N2FiZGM4NTQyN2QyZDJjNzcyZWQ1ZGI1MjBlNjkyYjUzM2M2MWJkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UVOs0C4XhqC7-SijF9Q3JCKxiKkWRi0V3qa1FJPRimw">

It works for me. The exact steps I followed are:

1. Clone the repository with git. From your terminal: `git clone https://github.com/lorenaacuna/GASTLI`
2. Create a new virtual environment (or conda, whichever your prefer). In my case: `virtualenv GASTLI_forIvatest`
3. Activate the environment: `source GASTLI_forIvatest/bin/activate`
4. Let's check what packages are installed by default in this new environment: `pip list`. The output is:
```
Package    Version
---------- -------
pip        24.3.1
setuptools 75.3.0
wheel      0.44.0
```

5. Go to GASTLI main folder (`cd GASTLI`). If you run `ls` from this directory, you should see the meson.build and pyproject.toml files. I run `pip install .` to install GASTLI and its dependencies, including pytest. If you run `pip list` again after installing GASTLI, this should be the output: 
```
Package         Version
--------------- -----------
contourpy       1.3.1
cycler          0.12.1
exceptiongroup  1.2.2
fonttools       4.55.0
gastli          0.9.1
h5py            3.12.1
iniconfig       2.0.0
kiwisolver      1.4.7
matplotlib      3.9.3
numpy           2.1.3
packaging       24.2
pandas          2.2.3
pillow          11.0.0
pip             24.3.1
pluggy          1.5.0
pyparsing       3.2.0
pytest          8.3.4
python-dateutil 2.9.0.post0
pytz            2024.2
scipy           1.14.1
setuptools      75.3.0
six             1.16.0
tomli           2.2.1
tzdata          2024.2
wheel           0.44.0

```
GASTLI and pytest are in the list. 
6. Go to the the test directory (`cd test`) and run `pytest`. The output for me was: 
```
(GASTLI_forIvatest) (base) mac-n-176:test acuna$ pytest
========================================================================= test session starts ==========================================================================
platform darwin -- Python 3.10.14, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/acuna/Desktop/MPIA2024/Code dev/JOSS GASTLI/Review/ivas test/GASTLI
configfile: pyproject.toml
collected 4 items                                                                                                                                                      

test_Coupling.py .                                                                                                                                               [ 25%]
test_GASTLI.py .                                                                                                                                                 [ 50%]
test_Thermal_evolution.py .                                                                                                                                      [ 75%]
test_atm_models_interp.py .                                                                                                                                      [100%]

==================================================================== 4 passed in 109.43s (0:01:49) =====================================================================
 [i] Allowed maximum number of iterations reached.
 
 [i] Convergence reached.
 [i] Convergence reached.
 [i] Convergence reached.
 [i] Allowed maximum number of iterations reached.
 
```

It takes a while for all tests to run (almost 2 minutes) but it run without interruptions. 

I'm going to close this issue since we resolved the installation problems. If you still have problems with pytest and testing it, please open a new issue
