### ISSUE TITLE
Performance verification

### ISSUE THREAD

**Issue by ivalaginja** [lorenaacuna/GASTLI#6]
For https://github.com/openjournals/joss-reviews/issues/7288.

Hi @lorenaacuna, in your paper you claim: "One single computation of the interior module (function `calc_radius` in the `GASTLI.int_planet` class) for the default precision and number of iterations takes 1.89 seconds in an Apple M2 CPU, with parallelization on 8 cores (four cores operating at 3.49 GHz and the other four cores operating at 2.42 GHz)."

Would you be able to provide the way to run/test this? I am trying to identify the code snippet I would have to time.

**Comment by lorenaacuna** [comment]
> Would you be able to provide the way to run/test this? I am trying to identify the code snippet I would have to time.

Hi @ivalaginja, the code snippet is the script `test_GASTLI.py` in the `test/` directory of the repository. I've added the commands to time the interior module function. If you run this script with `pytest` or with `python3 test_GASTLI.py` the output should be: 

```
Running interior structure model
 [i] Allowed maximum number of iterations reached.
 
Calculation time [s] =  1.8798940181732178

```

**Comment by ivalaginja** [comment]
Works for me, can be closed too now. Thanks!
